[workspace]
members = ["bronze_gc", "prototypes/city", "prototypes/city_gc", "prototypes/list_gc", "prototypes/draw_gc", "prototypes/tiny_gc", "prototypes/malloc", "prototypes/intcontainer", "bronze_derive"]
